DROP TABLE IF EXISTS mapbender.wms_search_table_tmp;
SELECT * INTO mapbender.wms_search_table_tmp FROM mapbender.search_wms_view;
DROP TABLE IF EXISTS mapbender.wms_search_table;
ALTER TABLE mapbender.wms_search_table_tmp RENAME TO wms_search_table;
CREATE INDEX gist_wst_the_geom ON wms_search_table USING gist (the_geom);
CREATE INDEX idx_wst_department ON wms_search_table USING btree (department);
CREATE INDEX idx_wst_md_topic_cats ON wms_search_table USING btree (md_topic_cats);
CREATE INDEX idx_wst_layer_id ON wms_search_table USING btree (layer_id);
CREATE INDEX idx_wst_load_count ON wms_search_table USING btree (load_count);
CREATE INDEX idx_wst_searchtext ON wms_search_table USING btree (searchtext);
CREATE INDEX idx_wst_wms_timestamp ON wms_search_table USING btree (wms_timestamp);
GRANT ALL ON TABLE mapbender.wms_search_table TO r_security WITH GRANT OPTION;
GRANT ALL ON TABLE mapbender.wms_search_table TO r_admin;

DROP TABLE IF EXISTS mapbender.wms_list_tmp;
SELECT * INTO mapbender.wms_list_tmp FROM mapbender.wms_list_view;
DROP TABLE IF EXISTS mapbender.wms_list;
ALTER TABLE mapbender.wms_list_tmp RENAME TO wms_list;
CREATE INDEX idx_wms_list_wms_id ON wms_list USING btree (wms_id);
GRANT ALL ON TABLE mapbender.wms_list TO r_security WITH GRANT OPTION;
GRANT ALL ON TABLE mapbender.wms_list TO r_admin;
